### ISSUE TITLE
Not compatible with python3 - execfile has been deprecated.

### ISSUE THREAD

**Issue by clipford** [rickypc/robotframework-dynamodbsqllibrary#1]
See the error that I received when building a docker container with this library. Dropping back to python2 fixed the issue but an alternative so that it will work with python3 useful.
 
File "/tmp/pip-install-27t48d4y/robotframework-dynamodbsqllibrary/setup.py", line 32, in <module>
        execfile(join(CWD, 'src', LIBRARY_NAME, 'version.py'))
    NameError: name 'execfile' is not defined

**Comment by samuelpcabral** [comment]
Hello @rickypc do you still active with this project? I am interested in fixing this problem (since I am using your library with python 3) and I would like to know if you are available to release a new version if I make a pull request

**Comment by rickypc** [comment]
Hi @samuelpcabral, please feel free to open a PR. I can help release a new version.

**Comment by samuelpcabral** [comment]
Hello @rickypc any plans to release the new version? thanks.

**Comment by rickypc** [comment]
Hello @samuelpcabral, v0.3.0 is released on 1/19/2023.

**Comment by samuelpcabral** [comment]
Great @rickypc  I see in pypi the new version. You may close this issue, if you want 👍

**Comment by rickypc** [comment]
Thanks, @samuelpcabral. I'm closing this issue.
