### ISSUE TITLE
execute select fail

### ISSUE THREAD

**Issue by seiya-annie** [rickypc/robotframework-dynamodbsqllibrary#2]
hi,

i execute a select like this:
Query DynamoDB     ${Lable}  select count(*) from ${tablename} where _id='${postid}'
but got error info: ParseException: Expected {";" | StringEnd} (at char 61), (line:1, col:62)

i try to add ";" at the end of sql, but still report same error.
do you know why? please help check

**Comment by samuelpcabral** [comment]
@seiya-annie This is because the query didn´t work.. you need to check the dql docs: https://dql.readthedocs.io/en/latest/topics/queries/index.html

**Comment by rickypc** [comment]
This doesn't sound like a library issue.
