### ISSUE TITLE
Install don´t work in new env

### ISSUE THREAD

**Issue by samuelpcabral** [rickypc/robotframework-dynamodbsqllibrary#4]
Trying to install in a new venv the library show this error:

```
Collecting robotframework-dynamodbsqllibrary
  Downloading robotframework-dynamodbsqllibrary-0.3.0.tar.gz (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 KB 1.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\scabra02\AppData\Local\Temp\pip-install-lb57sw85\robotframework-dynamodbsqllibrary_d3e93f7787d94a8dad6e137b3dfeca24\setup.py", line 29, in <module>
          from src.DynamoDBSQLLibrary.version import VERSION
        File "C:\Users\scabra02\AppData\Local\Temp\pip-install-lb57sw85\robotframework-dynamodbsqllibrary_d3e93f7787d94a8dad6e137b3dfeca24\src\DynamoDBSQLLibrary\__init__.py", line 24, in <module>
          from src.DynamoDBSQLLibrary.keywords import Assertion, Query, SessionManager
        File "C:\Users\scabra02\AppData\Local\Temp\pip-install-lb57sw85\robotframework-dynamodbsqllibrary_d3e93f7787d94a8dad6e137b3dfeca24\src\DynamoDBSQLLibrary\keywords\__init__.py", line 24, in <module>
          from src.DynamoDBSQLLibrary.keywords.assertion import Assertion
        File "C:\Users\scabra02\AppData\Local\Temp\pip-install-lb57sw85\robotframework-dynamodbsqllibrary_d3e93f7787d94a8dad6e137b3dfeca24\src\DynamoDBSQLLibrary\keywords\assertion.py", line 26, in <module>
          from dynamo3.exception import DynamoDBError
      ModuleNotFoundError: No module named 'dynamo3'
      [end of output]
```

**Comment by samuelpcabral** [comment]
fix in https://github.com/rickypc/robotframework-dynamodbsqllibrary/pull/5

**Comment by samuelpcabral** [comment]
Hello, @rickypc I found an problem when I was working on this issue... the version 0.3.0 is not working in a new env. the package has an error when is builded... see: https://pypi.org/project/robotframework-dynamodbsqllibrary/#files if you download the tar.gz file and discompact in your machine, the two __init__.py files have this problem:

```
from src.DynamoDBSQLLibrary.keywords import Assertion, Query, SessionManager
from src.DynamoDBSQLLibrary.version import get_version
```

```
from src.DynamoDBSQLLibrary.keywords.assertion import Assertion
from src.DynamoDBSQLLibrary.keywords.query import Query
from src.DynamoDBSQLLibrary.keywords.session import SessionManager
```

and when we import the Library in robot framework, this error appears: 

Error in file 'C:\Workspace\resources\gen_comnon_Keywords.resource’ on line 9: Importing library 'DynamoDBSQLLibrary’ failed: ModuleNotFoundError: No module named ‘src
Traceback (most recent call last):

When I created the dist for the versions 0.30 and 0.3.1 this src. don´t appears before the DynamoDBSQLLibrary inside __init__ I Used the command:

```
Python setup.py sdist
```

To help you, I will remove the dist folder from gitignore and send the tag.gz file to you in the merge request, then you could upload this file to pypi please?

Thank you and if you have some question, please contact me here 👍

**Comment by rickypc** [comment]
@samuelpcabral `dynamo3` should be installed by `dql` which is part of this library dependency. I'll take a look at the path error.

**Comment by samuelpcabral** [comment]
@rickypc I created an new venv and the first command that I send was: pip install robotframework-dynamodbsqllibrary, then I got the error of missin dynamo3.

About the path, I don´t know what is the root cause, as I mentioned in the pull request: https://github.com/rickypc/robotframework-dynamodbsqllibrary/pull/6 I just run "Python setup.py sdist" and the package was created without the path error.

Thanks.

**Comment by rickypc** [comment]
@samuelpcabral I made various adjustments and released version 0.3.1. Please give it a try.

**Comment by samuelpcabral** [comment]
@rickypc The version 0.3.1 is working very fine from pypi... thanks!
You can close this issue now 👍

**Comment by rickypc** [comment]
@samuelpcabral, thank you for confirming.
